### PR TITLE
Improve group description. remove old files not used

### LINKED ISSUE #29: remove vagrant file
we should remove vagrantfiles

### PR DESCRIPTION
**Pull request by MalloZup**
# description:

fix #29 #61

Tomorrow I might add more fixes . I will test the formula with SUMA a bit.

image

### CODE REVIEW

**Review by smpsgill — APPROVED** [review]
Thanks this looks fine

**Review by arbulu89 — CHANGES_REQUESTED** [review]
@MalloZup I think we should include the entry in the `Clustering` group together with the `Caasp` things. What do you think?
Anyway, both options are good.
Please, don't upgrade the package version yet. We will do it when we are sure we are going to ship, to include all the pending changes. In fact, this looks like a minor change in my opinion, so I would just change to `0.3.10` in any case.

**Comment by MalloZup** [comment]
ok waiting for this after suma update

**Comment by MalloZup** [comment]
@arbulu89  I think for the incoming update of suma we are ok. As discussed, is better to have not dependent groups

**Review by arbulu89 — APPROVED** [review]
@MalloZup Thanks for the changes!

**Pull request merged**
