### PR TITLE
Fixes for the SUSE Manager integration

### PR DESCRIPTION
**Pull request by cbosdo**
Fixing the input of dictionaries and the checkboxes

### CODE REVIEW

**Comment by arbulu89** [comment]
@Simranpal Could you have a look on this?
@cbosdo We would need to add an entry explaining the change in the `changes` file.
Something like `Fixes for the SUSE Manager integration` even works. This way we can ship to `Factory` as soon as it merged

**Comment by cbosdo** [comment]
> @cbosdo We would need to add an entry explaining the change in the `changes` file.

Done

**Review by smpsgill — APPROVED** [review]
@cbosdo thank you for testing and the fix.
I wanted to confirm if the `$optional` attribute is applicable to some fields only ? Mainly for the fields which we want to generate the pillar data.
For the cases you removed it from (mainly checkboxes) it is correct and it was irrelevant to have before.

**Comment by cbosdo** [comment]
> I wanted to confirm if the `$optional` attribute is applicable to some fields only ? Mainly for the fields which we want to generate the pillar data.

`$optional` is applicable to all fields from what I can tell, but if you have a field flagged as optional and the value is falsey the value isn't written to the pillar. This is what happened for the checkboxes: you never had the pillar value set to `False` and the checks based on this in the states where not working.

> For the cases you removed it from (mainly checkboxes) it is correct and it was irrelevant to have before.

I only tested this with a few properties (SBD device and watchdog), would be worth checking with other values, but I have no real clue about what all those config options mean and what they should generate.

**Comment by cbosdo** [comment]
looks like the state doesn't handle the checkboxes in a clean way... for some of them it only checks if they are defined. I'll fix this as well

**Comment by stefanotorresi** [comment]
Thanks a lot @cbosdo!!

**Pull request merged**
