### PR TITLE
Hotfix/add sshkeys default

### PR DESCRIPTION
**Pull request by arbulu89**
Hi guys,

We have been reported an issue in the formula. A regression that we have introduced in the latest code changes. Find the error message at then end.

Basically, the item `cluster.sshkeys` is not found, and this is because we removed the entry from defaults in: https://github.com/SUSE/habootstrap-formula/pull/68

I have added an empty default to avoid this scenario.

And with this, after finding that we are having several regressions, I have updated a bit our CI/Test system (removing the old `test` folder which was useless).
I have introduced more `pillar` options, and make the test file use all of them. This way we can cover new possibilities. Anyway, this won't be really useful if we don't take care of having the tests updated.

Sooo, I updated the version as well, as we need to ship this fix as soon as possible as it breaks the formula usage in a really common scenario (our cloud deployment for example)

```
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): [ERROR   ] Rendering exception occurred
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): Traceback (most recent call last):
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 394, in render_jinja_tmpl
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     output = template.render(**decoded_context)
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     return original_render(self, *args, **kwargs)
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     return self.environment.handle_exception(exc_info, True)
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     reraise(exc_type, exc_value, tb)
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     raise value.with_traceback(tb)
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   File "<template>", line 13, in top-level template code
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     return getattr(obj, attribute)
module.bluehorizon.module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'sshkeys'```

### CODE REVIEW

**Review by MalloZup — APPROVED** [review]
seems ok to me

**Review by stefanotorresi — APPROVED** [review]
lgtm

**Review by smpsgill — COMMENTED** [review]
Looks good. @arbulu89 for the test examples, I assume we need to keep the test pillars up to date with each change to pillar.
And I think with this change to CI, we need to update the Readme?
specially the Test section: https://github.com/SUSE/habootstrap-formula#test

**Comment by arbulu89** [comment]
> Looks good. @arbulu89 for the test examples, I assume we need to keep the test pillars up to date with each change to pillar.

The idea is that pillar usage changes are applied to the tests, or otherwise the tests fails. So, better we keep the tests the better. Unfortunately there is not such a tool to check the covered code in the tests for salt.

> And I think with this change to CI, we need to update the Readme?
> specially the Test section: https://github.com/SUSE/habootstrap-formula#test

Yes, you are right, I need to update the README file.
I will amend the change in the commit.

Edit:
Changed at 1e3661fe6b1532790c8a9acb9246f9cab7771fc5

**Review by smpsgill — APPROVED** [review]
Thanks for the changes, looks good now.

**Pull request merged**
