### PR TITLE
Moved templates into cluster/files - compatibility to gitfs

### PR DESCRIPTION
**Pull request by cschneemann**
Moved the templates directory into the cluster directory to be
compatible with gitfs.

Created files directory to do it like the other formulars do it.

### CODE REVIEW

**Comment by cschneemann** [comment]
@yeoldegrove 
Here the PR as asked from you in https://github.com/SUSE/sapnwbootstrap-formula/pull/97#issuecomment-1209139762

**Comment by yeoldegrove** [comment]
@cschneemann Could you also bump `_service` and `*.changes` so that we can directly release this?

**Review by yeoldegrove — CHANGES_REQUESTED** [review]
To use the same "simple" layout as in sapnwbootstrap-formula, could be just drop the `files` directory and name the dir just `cluster/templates`?

**Review by yeoldegrove — CHANGES_REQUESTED** [review]
@cschneemann Can't all references to `ftemplates` be removed? Also in the files section?

**Review by yeoldegrove — APPROVED** [review]
LGTM now. Also did a successfull test build and install.

**Pull request merged**
