### PR TITLE
Add OCFS2 support to the formula

### PR DESCRIPTION
**Pull request by cbosdo**

### CODE REVIEW

**Review by arbulu89 — COMMENTED** [review]
Hi @cbosdo ,
Some doubts. In the SUMA `form.yml` I read that multiple devices can be used.
How would this work?
In `sbd` we append the `json` method to convert to a list.
Give a look there. 
Maybe the current code works, I would like to check if single and multiple disks usage is implemented

**Comment by cbosdo** [comment]
> Maybe the current code works, I would like to check if single and multiple disks usage is implemented

Multiple disks for OCFS2 only works with the latest changes in `crmsh`

**Comment by cbosdo** [comment]
> In `sbd` we append the `json` method to convert to a list.
> Give a look there.
> Maybe the current code works, I would like to check if single and multiple disks usage is implemented

The `json` filter is not required here: jinja does it properly since the variable is already an array.

**Comment by cbosdo** [comment]
@arbulu89 what is the status of this PR?

**Review by arbulu89 — APPROVED** [review]

**Pull request merged**
