### PR TITLE
Remove the --no-overwrite-sshkey option

### PR DESCRIPTION
**Pull request by aleksei-burlakov**
The `crm cluster init/join` will create an ssh key if there is none. If there is an ssh key it will remain.

### CODE REVIEW

**Review by arbulu89 — COMMENTED** [review]
@aleksei-burlakov I don't understand these changes. Why are you removing the whole `overwrite` flag usage>

The fact that `no-overwrite-sshkey` is removed doesn't mean that the rest of the logic must go away.
In fact, this change would break our `ha-sap-terraform-deployments` usage, as it uses this flag to say the project to create a new key.

**Comment by aleksei-burlakov** [comment]
> @aleksei-burlakov I don't understand these changes. Why are you removing the whole `overwrite` flag usage>
> 
> The fact that `no-overwrite-sshkey` is removed doesn't mean that the rest of the logic must go away.
> In fact, this change would break our `ha-sap-terraform-deployments` usage, as it uses this flag to say the project to create a new key.

Thanks for reviewing. Yes, I understood this.  First, I don't think this overwriting works properly. It overwrites an ssh for all nodes, but the initialting (see cluster/sshkeys.sls:11). Second, is there a reason why an ssh key should be deliberately overwritten?

**Comment by aleksei-burlakov** [comment]
@arbulu89 I have reverted the version bump in the changes file.

**Comment by arbulu89** [comment]
> > @aleksei-burlakov I don't understand these changes. Why are you removing the whole `overwrite` flag usage>
> > The fact that `no-overwrite-sshkey` is removed doesn't mean that the rest of the logic must go away.
> > In fact, this change would break our `ha-sap-terraform-deployments` usage, as it uses this flag to say the project to create a new key.
> 
> Thanks for reviewing. Yes, I understood this. First, I don't think this overwriting works properly. It overwrites an ssh for all nodes, but the initialting (see cluster/sshkeys.sls:11). Second, is there a reason why an ssh key should be deliberately overwritten?

@aleksei-burlakov So, what happens now if no SSH keys are available? Is the formula still working? Or they are created later on by crmsh? Because SSH keys must exist for the correct functioning of crmsh.

I'm not agains removeing the overwrite option if the formula still creates a working cluster

**Review by arbulu89 — APPROVED** [review]

**Pull request merged**
